[phases.setup]
nixPkgs = ["python310", "gcc", "postgresql"]

[phases.install]
cmds = [
    "python3 -m venv /opt/venv",
    "/opt/venv/bin/pip install --upgrade pip",
    "/opt/venv/bin/pip install -r backend/requirements.txt"
]

[start]
cmd = "cd backend && /opt/venv/bin/python -m app.utils.seed && /opt/venv/bin/gunicorn -w 2 -k uvicorn.workers.UvicornWorker app.main:app --bind 0.0.0.0:$PORT"
